import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/views/header'
import Footer from '@/views/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My First Website',
  description: 'Generated by Ehsan Abdali',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
        </body>
    </html>
  )
}
