"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
let a = [];
let b = [];
let c = ['a', 10];
let d = [];
a = ["Pakistan"];
a.push("Ismamabad", "Lahore");
a.push("Karachi", "Multan", "Faisalabad");
b.push(1, 2, 3, 4, 5);
console.log(a);
console.log(b);
console.log(c);
console.log(d);
